#pragma once


enum DIRECTION {DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN ,DIR_END};

enum OBJID {OBJ_PLAYER, OBJ_BULLET,OBJ_BLOCK, OBJ_FLY,OBJ_HOPPER, OBJ_ENVY,OBJ_DOOR,OBJ_OBSTACLE, OBJ_MOUSE,OBJ_BUTTON,OBJ_MBULLET,OBJ_MACK, OBJ_END };

enum SCENEID { SC_LOGO, SC_STAGE,SC_STAGE2,SC_STAGE3, SC_END };