#pragma once


enum DIRECTION {DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN ,DIR_END};

enum OBJID {OBJ_PLAYER, OBJ_BULLET,OBJ_BLOCK, OBJ_FLY,OBJ_HOPPER,OBJ_DOOR,OBJ_FIRE, OBJ_MOUSE,OBJ_BUTTON, OBJ_END };

enum SCENEID { SC_LOGO, SC_STAGE,SC_STAGE2, SC_END };