#pragma once


enum DIRECTION {DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN ,DIR_END};

enum OBJID {OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_MOUSE, OBJ_END };

enum SCENEID { SC_LOGO, SC_MENU, SC_EDIT, SC_STAGE, SC_END };